name: "~[TF][REUSABLE_WORKFLOW]"

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Module to plan"
        required: true
        type: string
      region:
        description: "Region to plan"
        required: true
        type: string
        default: "us-west-2"
      command:
        description: "Command to plan or apply"
        required: true
        type: string
        default: "plan"
      environment:
        description: "Environment to plan"
        required: true
        type: string
        default: "DEV"
      target:
        description: "Target to plan"
        required: true
        type: string
      refresh:
        description: "Refresh state option"
        required: true
        type: boolean
        default: true
      disconnected:
        description: "Refresh state option"
        required: true
        type: boolean
        default: false
      is_pull_request:
        description: "Whether the workflow that triggered is a pull request or not"
        required: true
        type: boolean
        default: false
      bucket:
        description: "Bucket used for storing workflow logs"
        type: string
        required: true
      project_type:
        description: "Define the type of the project being executed, either corporate or health. Defaults to corporate"
        required: false
        type: string
        default: "corporate"
  workflow_call:
    # If you want to also use this workflow as reusable, keep this part
    inputs:
      module:
        description: "Module to plan"
        required: true
        type: string
      region:
        description: "Region to plan"
        required: true
        type: string
        default: "us-west-2"
      command:
        description: "Command to plan or apply"
        required: true
        type: string
        default: "plan"
      environment:
        description: "Environment to plan"
        required: true
        type: string
        default: "DEV"
      target:
        description: "Target to plan"
        required: true
        type: string
      refresh:
        description: "Refresh state option"
        required: true
        type: boolean
        default: true
      disconnected:
        description: "Refresh state option"
        required: true
        type: boolean
        default: false
      is_pull_request:
        description: "Whether the workflow that triggered is a pull request or not"
        required: true
        type: boolean
        default: false
      bucket:
        description: "Bucket used for storing workflow logs"
        type: string
        required: true
      project_type:
        description: "Define the type of the project being executed, either corporate or health. Defaults to corporate"
        required: false
        type: string
        default: "corporate"
    secrets:
      GHT:
        description: "GitHub token"
      DOCKERHUB_USERNAME:
        description: "Docker Hub username"
      DOCKERHUB_TOKEN:
        description: "Docker Hub token"

# Jobs section stays the same...
