name: Test Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      module:
        description: "Module to test"
        required: true
        type: string
      environment:
        description: "Environment (DEV/TEST/PROD)"
        required: true
        type: string
        default: "DEV"

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable_workflow.yml
    permissions:  # Add this block to grant permissions
      id-token: write  # Required for OIDC token generation
      contents: read   # Required for checkout
    with:
      module: ${{ inputs.module }}
      environment: ${{ inputs.environment }}
      region: "us-west-2"
      command: "plan"
      target: ""
      refresh: true
      disconnected: false
      is_pull_request: false
      bucket: "your-log-bucket-name"
      project_type: "corporate"
    secrets: inherit
